In [3]:
import pandas as pd
import numpy as np
from scipy.stats import chi2_contingency

In [4]:
df = pd.read_csv("../data/processed/accidentes_2024_limpio.csv")
df.shape

(51762, 88)

In [5]:
tabla_chi_via = pd.crosstab(
    df["TIPO_VIA_DESC"],
    df["ACCIDENTE_GRAVE"]
)

tabla_chi_via

ACCIDENTE_GRAVE                              0     1
TIPO_VIA_DESC
Autopista de peaje                          56    12
Autopista libre                           1837   152
Autovía                                   3554   383
Calle                                    24849  1624
Camino vecinal                             134    32
Carretera Convencional de calzada única   4557   671
Carretera Convencional de doble calzada    513    52
Otro                                     12219   851
Ramal de enlace                             87     8
Recinto delimitado                          27     1
Senda ciclable                              15     2
Vía ciclista                                 4     0
Vía de servicio                            100    10
Vía para automóviles                         8     4

In [6]:
chi2, p, dof, expected = chi2_contingency(tabla_chi_via)

chi2, p, dof

(np.float64(397.1264114293538), np.float64(9.045969409108789e-77), 13)

In [7]:
n = tabla_chi_via.to_numpy().sum()

phi2 = chi2 / n
r, k = tabla_chi_via.shape

v_cramer = np.sqrt(
    phi2 / min(k - 1, r - 1)
)

v_cramer

np.float64(0.08759087432825273)

In [ ]:
El test Chi-cuadrado indica una asociación estadísticamente significativa entre el tipo de vía y la gravedad del accidente (χ² = 397,13; p < 0,001).

Sin embargo, la V de Cramér obtenida es 0,088, lo que indica que la intensidad de la asociación es débil.

In [8]:
tabla_chi_zona = pd.crosstab(
    df["ZONA_DESC"],
    df["ACCIDENTE_GRAVE"]
)

chi2_zona, p_zona, dof_zona, expected_zona = chi2_contingency(tabla_chi_zona)

chi2_zona, p_zona, dof_zona

(np.float64(278.42618930429387), np.float64(4.6383956270291033e-60), 3)

In [9]:
n_zona = tabla_chi_zona.to_numpy().sum()

phi2_zona = chi2_zona / n_zona
r_zona, k_zona = tabla_chi_zona.shape

v_cramer_zona = np.sqrt(
    phi2_zona / min(k_zona - 1, r_zona - 1)
)

v_cramer_zona

np.float64(0.07334145431677293)

In [ ]:
El test Chi-cuadrado muestra una asociación estadísticamente significativa entre la zona y la gravedad del accidente (χ² = 278,43; p < 0,001).

La V de Cramér obtenida es 0,073, por lo que la intensidad de la asociación es débil.

In [10]:
tabla_chi_dia = pd.crosstab(
    df["DIA_SEMANA_DESC"],
    df["ACCIDENTE_GRAVE"]
)

chi2_dia, p_dia, dof_dia, expected_dia = chi2_contingency(tabla_chi_dia)

chi2_dia, p_dia, dof_dia

(np.float64(96.67417925928812), np.float64(1.2386943078374823e-18), 6)

In [11]:
n_dia = tabla_chi_dia.to_numpy().sum()

phi2_dia = chi2_dia / n_dia
r_dia, k_dia = tabla_chi_dia.shape

v_cramer_dia = np.sqrt(
    phi2_dia / min(k_dia - 1, r_dia - 1)
)

v_cramer_dia

np.float64(0.04321651304885856)

In [ ]:
El test Chi-cuadrado muestra una asociación estadísticamente significativa entre el día de la semana y la gravedad del accidente (χ² = 96,67; p < 0,001).

La V de Cramér obtenida es 0,043, lo que indica que la intensidad de la asociación es muy débil.

In [12]:
tabla_chi_provincia = pd.crosstab(
    df["PROVINCIA"],
    df["ACCIDENTE_GRAVE"]
)

chi2_provincia, p_provincia, dof_provincia, expected_provincia = chi2_contingency(
    tabla_chi_provincia
)

chi2_provincia, p_provincia, dof_provincia

(np.float64(48.77707289467783), np.float64(2.4646938064824967e-09), 5)

In [13]:
n_provincia = tabla_chi_provincia.to_numpy().sum()

phi2_provincia = chi2_provincia / n_provincia
r_provincia, k_provincia = tabla_chi_provincia.shape

v_cramer_provincia = np.sqrt(
    phi2_provincia / min(k_provincia - 1, r_provincia - 1)
)

v_cramer_provincia

np.float64(0.03069745300650315)

In [ ]:
El test Chi-cuadrado muestra una asociación estadísticamente significativa entre la provincia y la gravedad del accidente (χ² = 48,78; p < 0,001).

La V de Cramér obtenida es 0,031, por lo que la intensidad de la asociación es muy débil.

In [14]:
tabla_chi_tipo_accidente = pd.crosstab(
    df["TIPO_ACCIDENTE_DESC"],
    df["ACCIDENTE_GRAVE"]
)

chi2_tipo_accidente, p_tipo_accidente, dof_tipo_accidente, expected_tipo_accidente = chi2_contingency(
    tabla_chi_tipo_accidente
)

chi2_tipo_accidente, p_tipo_accidente, dof_tipo_accidente

(np.float64(898.9765086496611), np.float64(1.2977693871483838e-177), 20)

In [15]:
n_tipo_accidente = tabla_chi_tipo_accidente.to_numpy().sum()

phi2_tipo_accidente = chi2_tipo_accidente / n_tipo_accidente
r_tipo_accidente, k_tipo_accidente = tabla_chi_tipo_accidente.shape

v_cramer_tipo_accidente = np.sqrt(
    phi2_tipo_accidente / min(k_tipo_accidente - 1, r_tipo_accidente - 1)
)

v_cramer_tipo_accidente

np.float64(0.13178580914094185)

In [ ]:
El test Chi-cuadrado muestra una asociación estadísticamente significativa entre el tipo de accidente y la gravedad (χ² = 898,98; p < 0,001).

La V de Cramér obtenida es 0,132, lo que indica una asociación débil, aunque es la más intensa de las variables analizadas hasta el momento.

In [16]:
tabla_chi_fin_semana = pd.crosstab(
    df["FIN_SEMANA"],
    df["ACCIDENTE_GRAVE"]
)

chi2_fin_semana, p_fin_semana, dof_fin_semana, expected_fin_semana = chi2_contingency(
    tabla_chi_fin_semana
)

chi2_fin_semana, p_fin_semana, dof_fin_semana

(np.float64(91.00704174718969), np.float64(1.4316172934734901e-21), 1)

In [17]:
n_fin_semana = tabla_chi_fin_semana.to_numpy().sum()

phi2_fin_semana = chi2_fin_semana / n_fin_semana
r_fin_semana, k_fin_semana = tabla_chi_fin_semana.shape

v_cramer_fin_semana = np.sqrt(
    phi2_fin_semana / min(k_fin_semana - 1, r_fin_semana - 1)
)

v_cramer_fin_semana

np.float64(0.041930686665025724)

In [18]:
resumen_cramer = pd.DataFrame({
    "Relacion": [
        "Tipo de accidente ↔ gravedad",
        "Tipo de vía ↔ gravedad",
        "Zona ↔ gravedad",
        "Día de la semana ↔ gravedad",
        "Fin de semana ↔ gravedad",
        "Provincia ↔ gravedad"
    ],
    "V_Cramer": [
        v_cramer_tipo_accidente,
        v_cramer,
        v_cramer_zona,
        v_cramer_dia,
        v_cramer_fin_semana,
        v_cramer_provincia
    ]
}).sort_values("V_Cramer", ascending=False)

resumen_cramer.round(3)

                       Relacion  V_Cramer
0  Tipo de accidente ↔ gravedad     0.132
1        Tipo de vía ↔ gravedad     0.088
2               Zona ↔ gravedad     0.073
3   Día de la semana ↔ gravedad     0.043
4      Fin de semana ↔ gravedad     0.042
5          Provincia ↔ gravedad     0.031